export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const REGISTER_COMP_ADMIN_SUCCESS = "REGISTER_COMP_ADMIN_SUCCESS";
export const REGISTER_COMP_ADMIN_FAIL = "REGISTER_COMP_ADMIN_FAIL";
export const EDIT_COMP_ADMIN_SUCCESS = "EDIT_COMP_ADMIN_SUCCESS";
export const EDIT_COMP_ADMIN_FAIL = "EDIT_COMP_ADMIN_FAIL";

export const REGISTER_COMP_WORKER_SUCCESS = "REGISTER_COMP_WORKER_SUCCESS";
export const REGISTER_COMP_WORKER_FAIL = "REGISTER_COMP_WORKER_FAIL";
export const EDIT_COMP_WORKER_SUCCESS = "EDIT_COMP_WORKER_SUCCESS";
export const EDIT_COMP_WORKER_FAIL = "EDIT_COMP_WORKER_FAIL";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAIL = "CONFIRM_EMAIL_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const SET_MESSAGE_SUCCESS = "SET_MESSAGE_SUCCESS";
export const SET_MESSAGE_FAIL = "SET_MESSAGE_FAIL";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const AUTH = "AUTH";

export const GET_USERS = "GET_USERS";

export const RESET_PASSW_FAIL = "RESET_PASSW_FAIL";
export const RESET_PASSW_SUCCESS = "RESET_PASSW_SUCCESS";

export const NEW_PASSW_FAIL = "NEW_PASSW_FAIL";
export const NEW_PASSW_SUCCESS = "NEW_PASSW_SUCCESS";

export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_COMP_ADMIN = "SET_COMP_ADMIN";
export const CLEAR_COMP_ADMIN = "CLEAR_COMP_ADMIN";

export const SET_COMP_WORKER = "SET_COMP_WORKER";
export const CLEAR_COMP_WORKER = "CLEAR_COMP_WORKER";

export const SET_COMPANY = "SET_COMPANY";
export const CLEAR_COMPANY = "CLEAR_COMPANY";

export const REGISTER_EVENT_SUCCESS = "REGISTER_EVENT_SUCCESS";
export const REGISTER_EVENT_FAIL = "REGISTER_EVENT_FAIL";

export const SET_CURRENT_EVENT_LOC = "SET_CURRENT_EVENT_LOC";
export const CLEAR_CURRENT_EVENT_LOC = "CLEAR_CURRENT_EVENT_LOC";

export const SET_NEW_EVENT_LOC = "SET_NEW_EVENT_LOC";
export const CLEAR_NEW_EVENT_LOC = "CLEAR_NEW_EVENT_LOC";

export const SET_EVENT = "SET_EVENT";
export const CLEAR_EVENT = "CLEAR_EVENT";

export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS";
export const GET_COMPANY_LIST_FAIL = "GET_COMPANY_LIST_FAIL";

export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";

export const GET_COMPANY_ID_SUCCESS = "GET_COMPANY_ID_SUCCESS";
export const GET_COMPANY_ID_FAIL = "GET_COMPANY_ID_FAIL";

export const GET_COMP_ADMIN_LIST_SUCCESS = "GET_COMP_ADMIN_LIST_SUCCESS";
export const GET_COMP_ADMIN_LIST_FAIL = "GET_COMP_ADMIN_LIST_FAIL";

export const DELETE_COMP_ADMIN_SUCCESS = "DELETE_COMP_ADMIN_SUCCESS";
export const DELETE_COMP_ADMIN_FAIL = "DELETE_COMP_ADMIN_FAIL";

export const GET_COMP_ADMIN_ID_SUCCESS = "GET_COMP_ADMIN_ID_SUCCESS";
export const GET_COMP_ADMIN_ID_FAIL = "GET_COMP_ADMIN_ID_FAIL";

export const GET_COMP_WORKER_LIST_SUCCESS = "GET_COMP_WORKER_LIST_SUCCESS";
export const GET_COMP_WORKER_LIST_FAIL = "GET_COMP_WORKER_LIST_FAIL";

export const DELETE_COMP_WORKER_SUCCESS = "DELETE_COMP_WORKER_SUCCESS";
export const DELETE_COMP_WORKER_FAIL = "DELETE_COMP_WORKER_FAIL";

export const GET_COMP_WORKER_ID_SUCCESS = "GET_COMP_WORKER_ID_SUCCESS";
export const GET_COMP_WORKER_ID_FAIL = "GET_COMP_WORKER_ID_FAIL";

export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const GET_USER_ID_SUCCESS = "GET_USER_ID_SUCCESS";
export const GET_USER_ID_FAIL = "GET_USER_ID_FAIL";

export const GET_EVENT_LIST_SUCCESS = "GET_EVENT_LIST_SUCCESS";
export const GET_EVENT_LIST_FAIL = "GET_EVENT_LIST_FAIL";

export const GET_EVENT_LIST_ALL_SUCCESS = "GET_EVENT_LIST_ALL_SUCCESS";
export const GET_EVENT_LIST_ALL_FAIL = "GET_EVENT_LIST_ALL_FAIL";

export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const GET_EVENT_ID_SUCCESS = "GET_EVENT_ID_SUCCESS";
export const GET_EVENT_ID_FAIL = "GET_EVENT_ID_FAIL";

export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";

export const GET_ADRESS_SUCCESS = "GET_ADRESS_SUCCESS";
export const GET_ADRESS_FAIL = "GET_ADRESS_FAIL";

export const CLEAN_COMP_ADMIN_LIST = "CLEAN_COMP_ADMIN_LIST";
export const CLEAN_COMP_WORKER_LIST = "CLEAN_COMP_WORKER_LIST";
export const CLEAN_EVENT_LIST = "CLEAN_EVENT_LIST";
export const CLEAN_EVENT_LIST_ALL = "CLEAN_EVENT_LIST_ALL";
export const CLEAN_USER_LIST = "CLEAN_USER_LIST";

export const SET_EDIT_MODE = "SET_EDIT_MODE";

export const GET_EVENT_LIST_FAV_SUCCESS = "GET_EVENT_LIST_FAV_SUCCESS";
export const GET_EVENT_LIST_FAV_FAIL = "GET_EVENT_LIST_FAV_FAIL";

export const SET_FAVORITE_SUCCESS = "SET_FAVORITE_SUCCESS";
export const SET_FAVORITE_FAIL = "SET_FAVORITE_FAIL";

export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_FAIL = "DELETE_FAVORITE_FAIL";
