export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const REGISTER_COMP_ADMIN_SUCCESS = "REGISTER_COMP_ADMIN_SUCCESS";
export const REGISTER_COMP_ADMIN_FAIL = "REGISTER_COMP_ADMIN_FAIL";
export const EDIT_COMP_ADMIN_SUCCESS = "EDIT_COMP_ADMIN_SUCCESS";
export const EDIT_COMP_ADMIN_FAIL = "EDIT_COMP_ADMIN_FAIL";

export const REGISTER_COMP_WORKER_SUCCESS = "REGISTER_COMP_WORKER_SUCCESS";
export const REGISTER_COMP_WORKER_FAIL = "REGISTER_COMP_WORKER_FAIL";
export const EDIT_COMP_WORKER_SUCCESS = "EDIT_COMP_WORKER_SUCCESS";
export const EDIT_COMP_WORKER_FAIL = "EDIT_COMP_WORKER_FAIL";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAIL = "CONFIRM_EMAIL_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const AUTH = "AUTH";

export const GET_USERS = "GET_USERS";

export const RESET_PASSW_FAIL = "RESET_PASSW_FAIL";
export const RESET_PASSW_SUCCESS = "RESET_PASSW_SUCCESS";

export const NEW_PASSW_FAIL = "NEW_PASSW_FAIL";
export const NEW_PASSW_SUCCESS = "NEW_PASSW_SUCCESS";

export const SET_USER_ID = "SET_USER_ID";
export const CLEAR_USER_ID = "CLEAR_USER_ID";

export const SET_COMP_ADMIN_ID = "SET_COMP_ADMIN_ID";
export const CLEAR_COMP_ADMIN_ID = "CLEAR_COMP_ADMIN_ID";

export const SET_COMP_WORKER_ID = "SET_COMP_WORKER_ID";
export const CLEAR_COMP_WORKER_ID = "CLEAR_COMP_WORKER_ID";

export const SET_COMPANY_ID = "SET_COMPANY_ID";
export const CLEAR_COMPANY_ID = "CLEAR_COMPANY_ID";